spring:
  application:
    name: rmq-uc-consumer
  datasource:
    url: jdbc:mysql://localhost:3316/tmall_rec?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 1000

rocketmq:
  name-server: localhost:9876
  consumer:
    group: ${spring.application.name}
    topic: TestTopic
    pull-batch-size: 5