spring:
  application:
    name: rmq-uc-consumer
  datasource:
    url: jdbc:mysql://localhost:3316/tmall_rec?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 1000

#logging:
#  level:
#    root: debug

rocketmq:
  name-server: localhost:9876
  endpoints: localhost:8081
  consumer:
    group: rmq-uc-consumer
    pull-batch-size: 30
    topic: TxTopic
  producer:
    group: rmq-uc-prod
    send-message-timeout: 300000

rmq-uc:
  topic:
    test: TestTopic
    dev: DevTopic
    tx: TxTopic
  producer:
    group:
      tx: ${rocketmq.producer.group}-tx
      dev: ${rocketmq.producer.group}-dev
      test: ${rocketmq.producer.group}-test
  consumer:
    group:
      tx: ${rocketmq.consumer.group}-tx
      dev: ${rocketmq.consumer.group}-dev
      test: ${rocketmq.consumer.group}-test